// Storage configuration
// This file is auto-generated by setup-storage.js

const path = require('path');
const fs = require('fs');

function getStorageRootPath() {
  // Try to find the project root
  let currentDir = __dirname;
  while (currentDir !== path.dirname(currentDir)) {
    if (fs.existsSync(path.join(currentDir, 'package.json')) &&
      fs.existsSync(path.join(currentDir, 'apps'))) {
      return path.join(currentDir, 'storage');
    }
    currentDir = path.dirname(currentDir);
  }
  // Fallback to current directory + storage
  return path.join(process.cwd(), 'storage');
}

function getTempUploadPath() {
  return path.join(getStorageRootPath(), 'temp');
}

function getPermanentUploadPath(type, id) {
  return path.join(getStorageRootPath(), 'uploads', type, id);
}

function ensureDirectoryExists(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

module.exports = {
  getStorageRootPath,
  getTempUploadPath,
  getPermanentUploadPath,
  ensureDirectoryExists
};
