// Storage helper functions
// This file is auto-generated by setup-storage.js

const { getStorageRootPath, getTempUploadPath, getPermanentUploadPath, ensureDirectoryExists } = require('./storage.config');

class StorageHelper {
  static getStorageRoot() {
    return getStorageRootPath();
  }
  
  static getTempPath() {
    return getTempUploadPath();
  }
  
  static getPermanentPath(type, id) {
    return getPermanentUploadPath(type, id);
  }
  
  static ensureDirectory(dirPath) {
    ensureDirectoryExists(dirPath);
  }
  
  static moveTempFile(tempPath, permanentPath) {
    const fs = require('fs');
    const path = require('path');
    
    // Ensure destination directory exists
    const destDir = path.dirname(permanentPath);
    ensureDirectoryExists(destDir);
    
    // Move file
    fs.renameSync(tempPath, permanentPath);
    return permanentPath;
  }
  
  static deleteFile(filePath) {
    const fs = require('fs');
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  }
  
  static deleteDirectory(dirPath) {
    const fs = require('fs');
    if (fs.existsSync(dirPath)) {
      fs.rmSync(dirPath, { recursive: true, force: true });
    }
  }
}

module.exports = StorageHelper;
